name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Linting Python Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 on server directory
        run: |
          flake8 server/**/*.py
          echo "✅ Linted all Python files successfully"

  lint_function_js:
    name: Linting JavaScript Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JSHint
        run: npm install --global jshint

      - name: Run JSHint on database directory
        run: |
          jshint database/**/*.js
          echo "✅ Linted all JavaScript files successfully"
